# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "deploy"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "chaitanya1710/eks_nginx"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "master"
    git: "github"
    stage: "clone"

  RunPulumi:
    title: Deploying
    stage: deploy
    image: pulumi/pulumi
    working_directory: eks_nginx
    commands:
      - ls
      - yarn install
      - pulumi login
      - pulumi stack select dev
      - pulumi up --non-interactive --yes

